INSERT INTO treinos (grupo_muscular, exercicio) VALUES
('peito', 'Supino reto - 4 séries de 10 repetições'),
('peito', 'Supino inclinado com halteres - 3 séries de 12 repetições'),
('peito', 'Supino declinado - 3 séries de 10 repetições'),
('peito', 'Crucifixo reto - 3 séries de 15 repetições'),
('peito', 'Crucifixo inclinado - 3 séries de 12 repetições'),
('peito', 'Pullover - 4 séries de 10 repetições'),
('peito', 'Crossover - 3 séries de 12 repetições'),
('peito', 'Flexão de braço - 4 séries de 15 repetições'),
('costas', 'Puxada frontal - 4 séries de 10 repetições'),
('costas', 'Remada curvada - 3 séries de 12 repetições'),
('costas', 'Remada na máquina - 4 séries de 10 repetições'),
('costas', 'Puxada no pulley alto - 3 séries de 12 repetições'),
('costas', 'Good morning - 3 séries de 15 repetições'),
('costas', 'Deadlift - 4 séries de 8 repetições'),
('costas', 'Remada unilateral - 4 séries de 10 repetições'),
('costas', 'Puxada no pulley baixo - 3 séries de 12 repetições'),
('biceps', 'Curl com halteres - 3 séries de 15 repetições'),
('biceps', 'Curl de barra - 4 séries de 10 repetições'),
('biceps', 'Curl no pulley - 3 séries de 12 repetições'),
('biceps', 'Curl inclinado - 4 séries de 10 repetições'),
('biceps', 'Curl martelo - 3 séries de 12 repetições'),
('biceps', 'Curl concentrado - 4 séries de 10 repetições'),
('biceps', 'Curl com barra W - 3 séries de 15 repetições'),
('biceps', 'Curl Scott - 4 séries de 10 repetições'),
('triceps', 'Tríceps testa - 3 séries de 12 repetições'),
('triceps', 'Tríceps corda - 4 séries de 15 repetições'),
('triceps', 'Tríceps banco - 3 séries de 10 repetições'),
('triceps', 'Tríceps francês - 4 séries de 12 repetições'),
('triceps', 'Mergulho em banco - 3 séries de 10 repetições'),
('triceps', 'Tríceps máquina - 4 séries de 12 repetições'),
('triceps', 'Tríceps coice - 3 séries de 15 repetições'),
('triceps', 'Dips - 3 séries de 12 repetições'),
('perna', 'Agachamento livre - 4 séries de 8 repetições'),
('perna', 'Leg press - 3 séries de 12 repetições'),
('perna', 'Cadeira extensora - 4 séries de 10 repetições'),
('perna', 'Cadeira flexora - 3 séries de 12 repetições'),
('perna', 'Cadeira adutora - 3 séries de 15 repetições'),
('perna', 'Cadeira abdutora - 3 séries de 15 repetições'),
('perna', 'Stiff - 4 séries de 10 repetições'),
('perna', 'Panturrilha em pé - 4 séries de 20 repetições'),
('ombro', 'Desenvolvimento com halteres - 4 séries de 12 repetições'),
('ombro', 'Elevação lateral - 3 séries de 15 repetições'),
('ombro', 'Elevação frontal - 3 séries de 12 repetições'),
('ombro', 'Arnold press - 4 séries de 10 repetições'),
('ombro', 'Remada alta - 3 séries de 12 repetições'),
('ombro', 'Rotator cuff - 4 séries de 15 repetições'),
('ombro', 'Fly reverso - 3 séries de 15 repetições'),
('ombro', 'Shrug - 4 séries de 12 repetições'),
('trapezio', 'Encolhimento com halteres - 4 séries de 10 repetições'),
('trapezio', 'Remada alta - 3 séries de 12 repetições'),
('trapezio', 'Encolhimento na barra - 4 séries de 10 repetições'),
('trapezio', 'Face pull - 3 séries de 12 repetições'),
('trapezio', 'Encolhimento Smith - 3 séries de 10 repetições'),
('trapezio', 'Levantamento terra - 4 séries de 8 repetições'),
('trapezio', 'Dumbbell upright row - 3 séries de 12 repetições'),
('trapezio', 'Cable upright row - 4 séries de 10 repetições');